/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PinManagementRouteImport } from './routes/pin-management'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepositWithdrawRouteImport } from './routes/deposit-withdraw'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PinManagementRoute = PinManagementRouteImport.update({
  id: '/pin-management',
  path: '/pin-management',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositWithdrawRoute = DepositWithdrawRouteImport.update({
  id: '/deposit-withdraw',
  path: '/deposit-withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deposit-withdraw': typeof DepositWithdrawRoute
  '/login': typeof LoginRoute
  '/pin-management': typeof PinManagementRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deposit-withdraw': typeof DepositWithdrawRoute
  '/login': typeof LoginRoute
  '/pin-management': typeof PinManagementRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/deposit-withdraw': typeof DepositWithdrawRoute
  '/login': typeof LoginRoute
  '/pin-management': typeof PinManagementRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/deposit-withdraw'
    | '/login'
    | '/pin-management'
    | '/register'
    | '/transactions'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/deposit-withdraw'
    | '/login'
    | '/pin-management'
    | '/register'
    | '/transactions'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/deposit-withdraw'
    | '/login'
    | '/pin-management'
    | '/register'
    | '/transactions'
    | '/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DepositWithdrawRoute: typeof DepositWithdrawRoute
  LoginRoute: typeof LoginRoute
  PinManagementRoute: typeof PinManagementRoute
  RegisterRoute: typeof RegisterRoute
  TransactionsRoute: typeof TransactionsRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-management': {
      id: '/pin-management'
      path: '/pin-management'
      fullPath: '/pin-management'
      preLoaderRoute: typeof PinManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit-withdraw': {
      id: '/deposit-withdraw'
      path: '/deposit-withdraw'
      fullPath: '/deposit-withdraw'
      preLoaderRoute: typeof DepositWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DepositWithdrawRoute: DepositWithdrawRoute,
  LoginRoute: LoginRoute,
  PinManagementRoute: PinManagementRoute,
  RegisterRoute: RegisterRoute,
  TransactionsRoute: TransactionsRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
